<a href="https://colab.research.google.com/github/lintabong/Artificial-Intelligence/blob/main/Morton-Scan/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import cv2
import numpy
import random

In [2]:
img = numpy.ones([6, 9, 3], dtype="uint8")

for i in range(img.shape[0]):
    for j in range(img.shape[1]):
        for k in range(img.shape[2]):
            img[i][j][k] = random.randint(0,256)

print(img)

[[[243 112 101]
  [135 228 125]
  [148 146 133]
  [171 231 213]
  [  4 128 227]
  [231 174 185]
  [101   5 214]
  [227  92  59]
  [154  97 213]]

 [[ 55  50 167]
  [ 30  90 160]
  [130  22 172]
  [ 94  19 122]
  [ 92 162 182]
  [179 182  56]
  [  0 236   3]
  [ 37   7 123]
  [ 50 151 181]]

 [[192  81 123]
  [ 50   4  79]
  [200 121 162]
  [185 167  91]
  [ 55 120  64]
  [126 102 229]
  [236 171 253]
  [141 165  71]
  [225   2 136]]

 [[  8  27  51]
  [219  61 100]
  [ 38 176  49]
  [124 207  73]
  [224 105  26]
  [  2  18 238]
  [177  37 164]
  [127 127  27]
  [136  83   4]]

 [[187 117  17]
  [204 249  51]
  [ 21   5 204]
  [143 203  57]
  [ 49 114 168]
  [241 149  12]
  [208 203  10]
  [ 43 157  21]
  [131  50 219]]

 [[154 239 126]
  [ 95 156  16]
  [130 191  51]
  [253 159  78]
  [237 238 139]
  [241  56 206]
  [255 172  33]
  [  5 134 247]
  [112  15 226]]]


In [3]:
imgr = numpy.ones([6, 9, 1], dtype="uint8")

for i in range(img.shape[0]):
    for j in range(img.shape[1]):
        imgr[i][j] = (int(img[i][j][0]) + int(img[i][j][1]) + int(img[i][j][2]))/3

print(imgr)

[[[152]
  [162]
  [142]
  [205]
  [119]
  [196]
  [106]
  [126]
  [154]]

 [[ 90]
  [ 93]
  [108]
  [ 78]
  [145]
  [139]
  [ 79]
  [ 55]
  [127]]

 [[132]
  [ 44]
  [161]
  [147]
  [ 79]
  [152]
  [220]
  [125]
  [121]]

 [[ 28]
  [126]
  [ 87]
  [134]
  [118]
  [ 86]
  [126]
  [ 93]
  [ 74]]

 [[107]
  [168]
  [ 76]
  [134]
  [110]
  [134]
  [140]
  [ 73]
  [133]]

 [[173]
  [ 89]
  [124]
  [163]
  [204]
  [167]
  [153]
  [128]
  [117]]]


In [4]:
for i in range(imgr.shape[0]):
  print(imgr[i][0],imgr[i][1],imgr[i][2],imgr[i][3])

[152] [162] [142] [205]
[90] [93] [108] [78]
[132] [44] [161] [147]
[28] [126] [87] [134]
[107] [168] [76] [134]
[173] [89] [124] [163]


In [5]:
morton = []
s = 2
d = 2
for s in range(0,imgr.shape[0]-2,2):
  for d in range(0,imgr.shape[1]-2,2):
    for i in range(s,2+s):
      for j in range(d,2+d):
        morton.append(imgr[i][j][0])

print(morton)

[152, 162, 90, 93, 142, 205, 108, 78, 119, 196, 145, 139, 106, 126, 79, 55, 132, 44, 28, 126, 161, 147, 87, 134, 79, 152, 118, 86, 220, 125, 126, 93]
